In [1]:
import PublicDataReader as pdr
print(pdr.__version__)

>>> PublicDataReader Version : 2021.4.12

- Author : Wooil Jeong
- E-mail : wooil@kakao.com
- Github : https://github.com/WooilJeong/PublicDataReader
- Blog : https://wooiljeong.github.io

#### API 서비스 인증키 발급

In [2]:
# 공공 데이터 포털에서 발급 받은 서비스 인증키
serviceKey="0%2BxMMXkLj8nvKHhUgIzWPMdkHMGntGESg9ZCue80PT9KQl8KYHTo%2BT%2BPTrdmPLMowym5JNp5JRyY90zVGyvE2w%3D%3D"

# 국토교통부 실거래가 Open API 인스턴스 생성
molit = pdr.Transaction(serviceKey)

>>> 아파트매매 실거래자료 조회 서비스가 정상 작동합니다.
>>> 아파트매매 실거래 상세 자료 조회 서비스가 정상 작동합니다.
>>> 아파트 전월세 자료 조회 서비스가 정상 작동합니다.
>>> 아파트 분양권전매 신고 자료 조회 서비스가 정상 작동합니다.
>>> 오피스텔 매매 신고 조회 서비스가 정상 작동합니다.
>>> 오피스텔 전월세 신고 조회 서비스가 정상 작동합니다.
>>> 연립다세대 매매 실거래자료 조회 서비스가 정상 작동합니다.
>>> 연립다세대 전월세 실거래자료 조회 서비스가 정상 작동합니다.
>>> 단독/다가구 매매 실거래 조회 서비스가 정상 작동합니다.
>>> 단독/다가구 전월세 자료 조회 서비스가 정상 작동합니다.
>>> 토지 매매 신고 조회 서비스가 정상 작동합니다.
>>> 상업업무용 부동산 매매 신고 자료 조회 서비스가 정상 작동합니다.

#### 지역코드 검색

In [3]:
codeResult = molit.CodeFinder("강남구")
codeResult.head()

            법정동명  법정구코드
0      서울특별시 강남구  11680
1  서울특별시 강남구 역삼동  11680
2  서울특별시 강남구 개포동  11680
3  서울특별시 강남구 청담동  11680
4  서울특별시 강남구 삼성동  11680

#### 실거래자료 조회

In [4]:
# df_AptTrade = molit.AptTrade(11680, 202107)             # 아파트매매 실거래자료 조회
# df_AptTradeDetail = molit.AptTradeDetail(11680, 202107) # 아파트매매 실거래 상세 자료 조회
# df_AptRent = molit.AptRent(11680, 202107)               # 아파트 전월세 자료 조회
# df_AptOwnership = molit.AptOwnership(11680, 202107)     # 아파트 분양권전매 신고 자료 조회

# df_OffiTrade = molit.OffiTrade(11680, 202107)           # 오피스텔 매매 신고 조회
# df_OffiRent = molit.OffiRent(11680, 202107)             # 오피스텔 전월세 신고 조회
# df_RHTrade = molit.RHTrade(11680, 202107)               # 연립다세대 매매 실거래자료 조회
# df_RHRent = molit.RHRent(11680, 202107)                 # 연립다세대 전월세 실거래자료 조회

# df_DHTrade = molit.DHTrade(11680, 202107)               # 단독/다가구 매매 실거래 조회
# df_DHRent = molit.DHRent(11680, 202107)                 # 단독/다가구 전월세 자료 조회
# df_LandTrade = molit.LandTrade(11680, 202107)           # 토지 매매 신고 조회
# df_BizTrade = molit.BizTrade(11680, 202107)             # 상업업무용 부동산 매매 신고 자료 조회

In [5]:
# 아파트매매 실거래자료 조회
df_AptTrade = molit.AptTrade(11680, 202107)
df_AptTrade.head()

,지역코드,법정동,거래일,아파트,지번,전용면적,층,건축년도,거래금액
0,11680,개포동,2021-07-05,성원대치2단지아파트,12,39.53,15,1992,137000
1,11680,개포동,2021-07-10,삼익대청아파트,12,60.00,12,1992,175000
2,11680,대치동,2021-07-01,개포우성1,503,84.81,13,1983,280000
3,11680,대치동,2021-07-10,"대치우성아파트1동, 2동, 3동, 5동, 6동, 7동",63,115.59,9,1984,285000
4,11680,대치동,2021-07-12,테헤란로대우아이빌(891-6),891-6,33.11,7,2004,37800

In [6]:
# 아파트매매 실거래 상세 자료 조회
df_AptTradeDetail = molit.AptTradeDetail(11680, 202107)
df_AptTradeDetail.head()

,지역코드,법정동,거래일,아파트,지번,전용면적,층,건축년도,거래금액,법정동본번코드,...,법정동시군구코드,법정동읍면동코드,법정동지번코드,도로명,도로명건물본번호코드,도로명건물부번호코드,도로명시군구코드,도로명일련번호코드,도로명지상지하코드,도로명코드
0,11680,개포동,2021-07-05,성원대치2단지아파트,12,39.53,15,1992,137000,12,...,11680,10300,1,개포로109길,9,0,11680,1,0.0,4166040
1,11680,개포동,2021-07-10,삼익대청아파트,12,60.00,12,1992,175000,12,...,11680,10300,1,개포로109길,21,0,11680,1,0.0,4166040
2,11680,대치동,2021-07-01,개포우성1,503,84.81,13,1983,280000,503,...,11680,10600,1,선릉로,120,0,11680,0,NaN,3122006
3,11680,대치동,2021-07-10,"대치우성아파트1동, 2동, 3동, 5동, 6동, 7동",63,115.59,9,1984,285000,63,...,11680,10600,1,영동대로,230,0,11680,4,0.0,2122002
4,11680,대치동,2021-07-12,테헤란로대우아이빌(891-6),891-6,33.11,7,2004,37800,891,...,11680,10600,1,테헤란로,428,0,11680,3,0.0,3122010

In [7]:
# 아파트 전월세 자료 조회
df_AptRent = molit.AptRent(11680, 202107)
df_AptRent.head()

    지역코드  법정동        거래일         아파트    지번    전용면적   층  건축년도    보증금액  월세금액
0  11680  개포동 2021-07-01    래미안블레스티지  1280  99.967  12  2019  115500     0
1  11680  개포동 2021-07-01    개포주공 7단지   185  83.700  11  1983   70000     0
2  11680  개포동 2021-07-02  성원대치2단지아파트    12  33.180  15  1992   24150     0
3  11680  개포동 2021-07-03  성원대치2단지아파트    12  39.530   7  1992   46000     0
4  11680  개포동 2021-07-03    개포주공 5단지   187  83.170   3  1983   40000    46

In [8]:
# 아파트 분양권전매 신고 자료 조회
df_AptOwnership = molit.AptOwnership(11680, 202107)
df_AptOwnership.head()

조회할 자료가 없습니다.

Empty DataFrame
Columns: [지역코드, 법정동, 거래일, 시군구, 단지, 지번, 구분, 전용면적, 층, 거래금액]
Index: []

In [9]:
# 오피스텔 매매 신고 조회
df_OffiTrade = molit.OffiTrade(11680, 202107)
df_OffiTrade.head()

    지역코드  법정동        거래일  시군구                   단지      지번   전용면적   층   거래금액
0  11680  논현동 2021-07-01  강남구     강남구청역 에스케이 허브 블루   241-3  38.75   9  38000
1  11680  논현동 2021-07-06  강남구     강남구청역 에스케이 허브 블루   241-3  52.24   8  56000
2  11680  대치동 2021-07-09  강남구  CO-OP Residence/삼성역  945-29  13.96   3  14900
3  11680  대치동 2021-07-13  강남구          선릉역 롯데골드로즈2  890-59  39.00  12  29000
4  11680  대치동 2021-07-16  강남구             선릉역대우아이빌  890-49  30.10   2  19800

In [10]:
# 오피스텔 전월세 신고 조회
df_OffiRent = molit.OffiRent(11680, 202107)
df_OffiRent.head()

    지역코드  법정동        거래일  시군구              단지      지번   전용면적  층    보증금  월세
0  11680  개포동 2021-07-12  강남구        (1237-3)  1237-3  29.95  5   3000  80
1  11680  논현동 2021-07-03  강남구    \t(242-27)\t  242-27  43.92  8  40000   0
2  11680  대치동 2021-07-05  강남구       대치2차 아이파크  944-21  21.50  3  28300   0
3  11680  대치동 2021-07-07  강남구  선릉역 롯데골드로즈오피스텔  889-53  33.81  6  17000   0
4  11680  대치동 2021-07-08  강남구    대치트레비스타 101동  891-38  18.45  7  24000   0

In [11]:
# 연립다세대 매매 실거래자료 조회
df_RHTrade = molit.RHTrade(11680, 202107)
df_RHTrade.head()

    지역코드  법정동        거래일     연립다세대       지번   전용면적  건축년도  층   거래금액
0  11680  개포동 2021-07-02  개포 비버리하임   1193-5  27.72  2018  4  39500
1  11680  개포동 2021-07-02     아비채 2  1245-10  28.74  2016  3  38000
2  11680  개포동 2021-07-03       다인힐   1173-7  39.17  2016  2  34500
3  11680  개포동 2021-07-03    G-heim   1245-5  25.09  2017  5  39000
4  11680  개포동 2021-07-03      용성빌라   1179-1  38.44  1992  1  31000

In [12]:
# 연립다세대 전월세 실거래자료 조회
df_RHRent = molit.RHRent(11680, 202107)
df_RHRent.head()

    지역코드  법정동        거래일    연립다세대       지번   전용면적  건축년도  층   보증금액  월세금액
0  11680  개포동 2021-07-02  (160-6)    160-6  37.95  2012  3  22000     0
1  11680  개포동 2021-07-02     동산빌라  1164-29  42.84  1996  3  30000     0
2  11680  개포동 2021-07-07  칠성빌라 가동   1165-4  50.28  1989  2  25000     0
3  11680  개포동 2021-07-07    W하우스2  1234-10  19.75  2013  2   1000    57
4  11680  개포동 2021-07-07  칠성빌라 가동   1165-4  50.28  1989  2  25000     0

In [13]:
# 단독/다가구 매매 실거래 조회
df_DHTrade = molit.DHTrade(11680, 202107)
df_DHTrade.head()

    지역코드  법정동        거래일 주택유형   대지면적      연면적  건축년도     거래금액
0  11680  논현동 2021-07-06   단독  340.5  1048.49  1989  1550000
1  11680  신사동 2021-07-03   단독   87.4   110.85  1975   302000

In [14]:
# 단독/다가구 전월세 자료 조회
df_DHRent = molit.DHRent(11680, 202107)
df_DHRent.head()

    지역코드  법정동        거래일   계약면적   보증금액  월세금액
0  11680  개포동 2021-07-03  62.12  15000    20
1  11680  개포동 2021-07-03  61.00  25000     0
2  11680  개포동 2021-07-03  62.12  15000    20
3  11680  개포동 2021-07-05  38.16  15000     0
4  11680  개포동 2021-07-05  26.98   3000     0

In [15]:
# 토지 매매 신고 조회
df_LandTrade = molit.LandTrade(11680, 202107)
df_LandTrade.head()

    지역코드  법정동        거래일  시군구       용도지역  지목  지분거래구분   거래면적    거래금액
0  11680  대치동 2021-07-16  강남구  제1종전용주거지역  도로     NaN  114.0   10000
1  11680  세곡동 2021-07-09  강남구     개발제한구역   전     NaN   63.0    5981
2  11680  세곡동 2021-07-09  강남구     개발제한구역   답     NaN  528.0   47991
3  11680  세곡동 2021-07-09  강남구     개발제한구역   답     NaN  143.0   15798
4  11680  세곡동 2021-07-09  강남구     개발제한구역   전     NaN    NaN  125430

In [16]:
# 상업업무용 부동산 매매 신고 자료 조회
df_BizTrade = molit.BizTrade(11680, 202107)
df_BizTrade.head()

,지역코드,법정동,거래일,시군구,용도지역,유형,대지면적,구분,건물면적,건물주용도,건축년도,층,거래금액
0,11680,개포동,2021-07-12,강남구,제3종일반주거,집합,NaN,NaN,26.18,판매,2011,NaN,24000
1,11680,개포동,2021-07-20,강남구,일반상업,집합,NaN,NaN,18.48,제1종근린생활,1984,NaN,4000
2,11680,논현동,2021-07-01,강남구,제3종일반주거,일반,1027.2,NaN,2758.95,업무,1986,NaN,4000000
3,11680,논현동,2021-07-01,강남구,제2종일반주거,집합,NaN,NaN,19.32,제1종근린생활,1978,NaN,13500
4,11680,논현동,2021-07-01,강남구,제2종일반주거,집합,NaN,NaN,19.32,제1종근린생활,1978,NaN,13500

#### 지역, 기간 별 데이터 프레임 만들기

In [17]:
## Function(API서비스 메서드, 지역코드(5자리), 시작월(YYYYMM), 종료월(YYYYMM))

# df_AptTradeSum = molit.DataCollector(molit.AptTrade, 11680, 202101, 202107)
# df_AptTradeDetailSum = molit.DataCollector(molit.AptTradeDetail, 11680, 202101, 202107)
# df_AptRentSum = molit.DataCollector(molit.AptRent, 11680, 202101, 202107)
# df_AptOwnershipSum = molit.DataCollector(molit.AptOwnership, 11680, 202101, 202107)

# df_OffiTradeSum = molit.DataCollector(molit.OffiTrade, 11680, 202101, 202107)
# df_OffiRentSum = molit.DataCollector(molit.OffiRent, 11680, 202101, 202107)
# df_RHTradeSum = molit.DataCollector(molit.RHTrade, 11680, 202101, 202107)
# df_RHRentSum = molit.DataCollector(molit.RHRent, 11680, 202101, 202107)

# df_DHTradeSum = molit.DataCollector(molit.DHTrade, 11680, 202101, 202107)
# df_DHRentSum = molit.DataCollector(molit.DHRent, 11680, 202101, 202107)
# df_LandTradeSum = molit.DataCollector(molit.LandTrade, 11680, 202101, 202107)
# df_BizTradeSum = molit.DataCollector(molit.BizTrade, 11680, 202101, 202107)

In [18]:
df_AptTradeSum = molit.DataCollector(molit.AptTrade, 11680, 202101, 202107)
df_AptTradeSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

    지역코드  법정동        거래일            아파트   지번   전용면적   층  건축년도    거래금액
0  11680  개포동 2021-01-01       개포주공 6단지  185  53.06   3  1983  178000
1  11680  개포동 2021-01-01  현대1차101동~106동  653  95.40   9  1984  215000
2  11680  개포동 2021-01-03            우성8  179  78.93   3  1987  181000
3  11680  개포동 2021-01-04     성원대치2단지아파트   12  49.86  12  1992  150000
4  11680  개포동 2021-01-04        삼익대청아파트   12  60.00  13  1992  157000

In [19]:
df_AptTradeDetailSum = molit.DataCollector(molit.AptTradeDetail, 11680, 202101, 202107)
df_AptTradeDetailSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

,지역코드,법정동,거래일,아파트,지번,전용면적,층,건축년도,거래금액,법정동본번코드,...,법정동시군구코드,법정동읍면동코드,법정동지번코드,도로명,도로명건물본번호코드,도로명건물부번호코드,도로명시군구코드,도로명일련번호코드,도로명지상지하코드,도로명코드
0,11680,개포동,2021-01-01,개포주공 6단지,185,53.06,3,1983,178000,185,...,11680,10300,1.0,개포로,516,0,11680,1,0.0,3122001
1,11680,개포동,2021-01-01,현대1차101동~106동,653,95.40,9,1984,215000,653,...,11680,10300,1.0,개포로,303,0,11680,1,0.0,3122001
2,11680,개포동,2021-01-03,우성8,179,78.93,3,1987,181000,179,...,11680,10300,1.0,개포로,411,0,11680,1,0.0,3122001
3,11680,개포동,2021-01-04,삼익대청아파트,12,60.00,13,1992,157000,12,...,11680,10300,1.0,개포로109길,21,0,11680,1,0.0,4166040
4,11680,개포동,2021-01-04,성원대치2단지아파트,12,49.86,12,1992,150000,12,...,11680,10300,1.0,개포로109길,9,0,11680,1,0.0,4166040

In [20]:
df_AptRentSum = molit.DataCollector(molit.AptRent, 11680, 202101, 202107)
df_AptRentSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

    지역코드  법정동        거래일         아파트    지번   전용면적   층  건축년도   보증금액  월세금액
0  11680  개포동 2021-01-01   개포래미안포레스트  1282  49.92   5  2020  50000   130
1  11680  개포동 2021-01-01   개포래미안포레스트  1282  59.92   3  2020  20444    66
2  11680  개포동 2021-01-02  성원대치2단지아파트    12  49.86   4  1992  37800     0
3  11680  개포동 2021-01-02  성원대치2단지아파트    12  33.18  15  1992  33000     0
4  11680  개포동 2021-01-03    개포주공 7단지   185  83.70  12  1983  85000     0

In [21]:
df_AptOwnershipSum = molit.DataCollector(molit.AptOwnership, 11680, 202101, 202107)
df_AptOwnershipSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107
조회할 자료가 없습니다.

    지역코드  법정동        거래일  시군구              단지     지번 구분     전용면적   층    거래금액
0  11680  개포동 2021-01-04  강남구  디에이치 퍼스티어 아이파크  660-1  입  59.9742  18  194005
1  11680  개포동 2021-01-07  강남구       개포래미안포레스트   1282  입  49.9200   7  180000
2  11680  개포동 2021-01-09  강남구  디에이치 퍼스티어 아이파크  660-1  입  84.9956  11  255903
3  11680  개포동 2021-01-18  강남구       개포래미안포레스트   1282  입  74.6600  12  240000
4  11680  개포동 2021-01-20  강남구       개포프레지던스자이    189  입  84.5978  26  282000

In [22]:
df_OffiTradeSum = molit.DataCollector(molit.OffiTrade, 11680, 202101, 202107)
df_OffiTradeSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

    지역코드  법정동        거래일  시군구        단지      지번   전용면적   층    거래금액
0  11680  개포동 2021-01-06  강남구      메트하임  186-13  22.00  15   34800
1  11680  개포동 2021-01-13  강남구      대청타워    13-3  31.91  14   23500
2  11680  개포동 2021-01-14  강남구      대청타워    13-3  31.91  15   21500
3  11680  논현동 2021-01-02  강남구     강남파라곤   241-1  75.94  10  119000
4  11680  논현동 2021-01-06  강남구  \t(96)\t      96  22.05   6   15500

In [23]:
df_OffiRentSum = molit.DataCollector(molit.OffiRent, 11680, 202101, 202107)
df_OffiRentSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

,지역코드,법정동,거래일,시군구,단지,지번,전용면적,층,보증금,월세
0,11680,개포동,2021-01-19,강남구,메트하임,186-13,22.00,14,1000,90
1,11680,개포동,2021-01-21,강남구,CCRU오피스텔,1229-6,50.04,3,33600,0
2,11680,개포동,2021-01-23,강남구,하우징허브럭스,1229-10,56.86,4,42000,0
3,11680,개포동,2021-01-26,강남구,하우징허브럭스,1229-10,56.86,5,10500,60
4,11680,논현동,2021-01-07,강남구,강남구청역 에스케이 허브 블루,241-3,34.57,10,1000,125

In [24]:
df_RHTradeSum = molit.DataCollector(molit.RHTrade, 11680, 202101, 202107)
df_RHTradeSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

    지역코드  법정동        거래일          연립다세대      지번   전용면적  건축년도  층   거래금액
0  11680  개포동 2021-01-02  우성파크빌라(161-0)     161  44.00  1993 -1  27500
1  11680  개포동 2021-01-05          베네스트빌  1179-6  50.18  2002  4  51500
2  11680  개포동 2021-01-05          베네스트빌  1179-6  50.18  2002  4  51500
3  11680  개포동 2021-01-05  파크힐빌리지(160-4)   160-4  36.44  1995  3  38000
4  11680  개포동 2021-01-06          베네스트빌  1179-6  44.28  2002  2  36000

In [25]:
df_RHRentSum = molit.DataCollector(molit.RHRent, 11680, 202101, 202107)
df_RHRentSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

    지역코드  법정동        거래일  연립다세대       지번    전용면적  건축년도  층   보증금액  월세금액
0  11680  개포동 2021-01-01   명성빌라   1201-6  55.100  1993  3   7000    60
1  11680  개포동 2021-01-03   동산빌라  1164-29  42.600  1996  4  16800     0
2  11680  개포동 2021-01-04  새롬그린빌  1219-10  56.790  1995  1  30450     0
3  11680  개포동 2021-01-04    호원빌   1171-9  45.885  2016  2  26250     0
4  11680  개포동 2021-01-05    드림빌   660-34  14.880  2012  2   7500     0

In [26]:
df_DHTradeSum = molit.DataCollector(molit.DHTrade, 11680, 202101, 202107)
df_DHTradeSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

    지역코드  법정동        거래일 주택유형   대지면적     연면적  건축년도    거래금액
0  11680  개포동 2021-01-07   단독  540.1  498.42  1997  820000
1  11680  논현동 2021-01-19   단독  298.8  453.29  1978  630000
2  11680  논현동 2021-01-19  다가구  186.1  419.52  1995  300000
3  11680  논현동 2021-01-22   단독  295.6  144.50  1976  520000
4  11680  대치동 2021-01-18   단독  165.9  131.50  1977  500000

In [27]:
df_DHRentSum = molit.DataCollector(molit.DHRent, 11680, 202101, 202107)
df_DHRentSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

    지역코드  법정동        거래일   계약면적   보증금액  월세금액
0  11680  개포동 2021-01-04  82.00  42000     0
1  11680  개포동 2021-01-05  45.00   2000    80
2  11680  개포동 2021-01-05  44.96  15000    33
3  11680  개포동 2021-01-05  44.96  15000    33
4  11680  개포동 2021-01-06  16.50   1000    51

In [28]:
df_LandTradeSum = molit.DataCollector(molit.LandTrade, 11680, 202101, 202107)
df_LandTradeSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

    지역코드  법정동        거래일  시군구       용도지역 지목  지분거래구분   거래면적     거래금액
0  11680  개포동 2021-01-14  강남구     자연녹지지역  답     NaN   43.0    15712
1  11680  논현동 2021-01-13  강남구  제3종일반주거지역  대     NaN  426.0  1415000
2  11680  논현동 2021-01-14  강남구  제2종일반주거지역  대     NaN  172.0   466749
3  11680  논현동 2021-01-14  강남구  제2종일반주거지역  대     NaN  172.0   466749
4  11680  대치동 2021-01-07  강남구  제3종일반주거지역  전     NaN    4.0    25000

In [29]:
df_BizTradeSum = molit.DataCollector(molit.BizTrade, 11680, 202101, 202107)
df_BizTradeSum.head()

>>> LAWD_CD : 11680 DEAL_YMD : 202101
>>> LAWD_CD : 11680 DEAL_YMD : 202102
>>> LAWD_CD : 11680 DEAL_YMD : 202103
>>> LAWD_CD : 11680 DEAL_YMD : 202104
>>> LAWD_CD : 11680 DEAL_YMD : 202105
>>> LAWD_CD : 11680 DEAL_YMD : 202106
>>> LAWD_CD : 11680 DEAL_YMD : 202107

,지역코드,법정동,거래일,시군구,용도지역,유형,대지면적,구분,건물면적,건물주용도,건축년도,층,거래금액
0,11680,개포동,2021-01-08,강남구,일반상업,집합,NaN,NaN,31.91,업무,1997.0,22.0,21500
1,11680,개포동,2021-01-15,강남구,제2종일반주거,집합,NaN,NaN,56.25,제2종근린생활,2019.0,NaN,150000
2,11680,개포동,2021-01-29,강남구,제3종일반주거,집합,NaN,NaN,103.88,제1종근린생활,2011.0,2.0,34000
3,11680,개포동,2021-01-30,강남구,일반상업,집합,NaN,NaN,17.68,판매,1984.0,NaN,10777
4,11680,논현동,2021-01-07,강남구,제3종일반주거,일반,231.1,NaN,599.98,제1종근린생활,1994.0,NaN,840000